# Generated by Django 5.2.10 on 2026-01-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bun_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bunbase',
            options={'verbose_name': 'bun base', 'verbose_name_plural': 'bun base'},
        ),
        migrations.AddField(
            model_name='bunbase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
